### PR TITLE
Correcting an American idiom.

### PR DESCRIPTION
**Pull request by rhyolight**

### CODE REVIEW

**Comment by passiweinberger** [comment]
;)

**Comment by passiweinberger** [comment]
Btw. I'm fine with you just changing things like that.:) No need for PRs in these cases :)

**Comment by rhyolight** [comment]
This is the way I like to work, though. It gives you a chance to see what
is being done to your repo. :)

---

Matt Taylor
OS Community Flag-Bearer
Numenta

**Comment by passiweinberger** [comment]
Ok thats a point ;)

**Comment by passiweinberger** [comment]
Plus I learn proper english :P :+1:

**Pull request merged**
